package main

import (
	"bytes"
	"fmt"
	"os"
	"text/template"
	"time"
)

const (
	ACKNOWLEDGE_HOST_PROBLEM = iota
	ACKNOWLEDGE_SVC_PROBLEM
	ADD_HOST_COMMENT
	ADD_SVC_COMMENT
	CHANGE_CONTACT_HOST_NOTIFICATION_TIMEPERIOD
	CHANGE_CONTACT_MODATTR
	CHANGE_CONTACT_MODHATTR
	CHANGE_CONTACT_MODSATTR
	CHANGE_CONTACT_SVC_NOTIFICATION_TIMEPERIOD
	CHANGE_CUSTOM_CONTACT_VAR
	CHANGE_CUSTOM_HOST_VAR
	CHANGE_CUSTOM_SVC_VAR
	CHANGE_GLOBAL_HOST_EVENT_HANDLER
	CHANGE_GLOBAL_SVC_EVENT_HANDLER
	CHANGE_HOST_CHECK_COMMAND
	CHANGE_HOST_CHECK_TIMEPERIOD
	CHANGE_HOST_EVENT_HANDLER
	CHANGE_HOST_MODATTR
	CHANGE_MAX_HOST_CHECK_ATTEMPTS
	CHANGE_MAX_SVC_CHECK_ATTEMPTS
	CHANGE_NORMAL_HOST_CHECK_INTERVAL
	CHANGE_NORMAL_SVC_CHECK_INTERVAL
	CHANGE_RETRY_HOST_CHECK_INTERVAL
	CHANGE_RETRY_SVC_CHECK_INTERVAL
	CHANGE_SVC_CHECK_COMMAND
	CHANGE_SVC_CHECK_TIMEPERIOD
	CHANGE_SVC_EVENT_HANDLER
	CHANGE_SVC_MODATTR
	CHANGE_SVC_NOTIFICATION_TIMEPERIOD
	DELAY_HOST_NOTIFICATION
	DELAY_SVC_NOTIFICATION
	DEL_ALL_HOST_COMMENTS
	DEL_ALL_SVC_COMMENTS
	DEL_HOST_COMMENT
	DEL_HOST_DOWNTIME
	DEL_SVC_COMMENT
	DEL_SVC_DOWNTIME
	DISABLE_ALL_NOTIFICATIONS_BEYOND_HOST
	DISABLE_CONTACTGROUP_HOST_NOTIFICATIONS
	DISABLE_CONTACTGROUP_SVC_NOTIFICATIONS
	DISABLE_CONTACT_HOST_NOTIFICATIONS
	DISABLE_CONTACT_SVC_NOTIFICATIONS
	DISABLE_EVENT_HANDLERS
	DISABLE_FAILURE_PREDICTION
	DISABLE_FLAP_DETECTION
	DISABLE_HOSTGROUP_HOST_CHECKS
	DISABLE_HOSTGROUP_HOST_NOTIFICATIONS
	DISABLE_HOSTGROUP_PASSIVE_HOST_CHECKS
	DISABLE_HOSTGROUP_PASSIVE_SVC_CHECKS
	DISABLE_HOSTGROUP_SVC_CHECKS
	DISABLE_HOSTGROUP_SVC_NOTIFICATIONS
	DISABLE_HOST_AND_CHILD_NOTIFICATIONS
	DISABLE_HOST_CHECK
	DISABLE_HOST_EVENT_HANDLER
	DISABLE_HOST_FLAP_DETECTION
	DISABLE_HOST_FRESHNESS_CHECKS
	DISABLE_HOST_NOTIFICATIONS
	DISABLE_HOST_SVC_CHECKS
	DISABLE_HOST_SVC_NOTIFICATIONS
	DISABLE_NOTIFICATIONS
	DISABLE_PASSIVE_HOST_CHECKS
	DISABLE_PASSIVE_SVC_CHECKS
	DISABLE_PERFORMANCE_DATA
	DISABLE_SERVICEGROUP_HOST_CHECKS
	DISABLE_SERVICEGROUP_HOST_NOTIFICATIONS
	DISABLE_SERVICEGROUP_PASSIVE_HOST_CHECKS
	DISABLE_SERVICEGROUP_PASSIVE_SVC_CHECKS
	DISABLE_SERVICEGROUP_SVC_CHECKS
	DISABLE_SERVICEGROUP_SVC_NOTIFICATIONS
	DISABLE_SERVICE_FLAP_DETECTION
	DISABLE_SERVICE_FRESHNESS_CHECKS
	DISABLE_SVC_CHECK
	DISABLE_SVC_EVENT_HANDLER
	DISABLE_SVC_FLAP_DETECTION
	DISABLE_SVC_NOTIFICATIONS
	ENABLE_ALL_NOTIFICATIONS_BEYOND_HOST
	ENABLE_CONTACTGROUP_HOST_NOTIFICATIONS
	ENABLE_CONTACTGROUP_SVC_NOTIFICATIONS
	ENABLE_CONTACT_HOST_NOTIFICATIONS
	ENABLE_CONTACT_SVC_NOTIFICATIONS
	ENABLE_EVENT_HANDLERS
	ENABLE_FAILURE_PREDICTION
	ENABLE_FLAP_DETECTION
	ENABLE_HOSTGROUP_HOST_CHECKS
	ENABLE_HOSTGROUP_HOST_NOTIFICATIONS
	ENABLE_HOSTGROUP_PASSIVE_HOST_CHECKS
	ENABLE_HOSTGROUP_PASSIVE_SVC_CHECKS
	ENABLE_HOSTGROUP_SVC_CHECKS
	ENABLE_HOSTGROUP_SVC_NOTIFICATIONS
	ENABLE_HOST_AND_CHILD_NOTIFICATIONS
	ENABLE_HOST_CHECK
	ENABLE_HOST_EVENT_HANDLER
	ENABLE_HOST_FLAP_DETECTION
	ENABLE_HOST_FRESHNESS_CHECKS
	ENABLE_HOST_NOTIFICATIONS
	ENABLE_HOST_SVC_CHECKS
	ENABLE_HOST_SVC_NOTIFICATIONS
	ENABLE_NOTIFICATIONS
	ENABLE_PASSIVE_HOST_CHECKS
	ENABLE_PASSIVE_SVC_CHECKS
	ENABLE_PERFORMANCE_DATA
	ENABLE_SERVICEGROUP_HOST_CHECKS
	ENABLE_SERVICEGROUP_HOST_NOTIFICATIONS
	ENABLE_SERVICEGROUP_PASSIVE_HOST_CHECKS
	ENABLE_SERVICEGROUP_PASSIVE_SVC_CHECKS
	ENABLE_SERVICEGROUP_SVC_CHECKS
	ENABLE_SERVICEGROUP_SVC_NOTIFICATIONS
	ENABLE_SERVICE_FRESHNESS_CHECKS
	ENABLE_SVC_CHECK
	ENABLE_SVC_EVENT_HANDLER
	ENABLE_SVC_FLAP_DETECTION
	ENABLE_SVC_NOTIFICATIONS
	PROCESS_FILE
	PROCESS_HOST_CHECK_RESULT
	PROCESS_SERVICE_CHECK_RESULT
	READ_STATE_INFORMATION
	REMOVE_HOST_ACKNOWLEDGEMENT
	REMOVE_SVC_ACKNOWLEDGEMENT
	RESTART_PROGRAM
	SAVE_STATE_INFORMATION
	SCHEDULE_AND_PROPAGATE_HOST_DOWNTIME
	SCHEDULE_AND_PROPAGATE_TRIGGERED_HOST_DOWNTIME
	SCHEDULE_FORCED_HOST_CHECK
	SCHEDULE_FORCED_HOST_SVC_CHECKS
	SCHEDULE_FORCED_SVC_CHECK
	SCHEDULE_HOSTGROUP_HOST_DOWNTIME
	SCHEDULE_HOSTGROUP_SVC_DOWNTIME
	SCHEDULE_HOST_CHECK
	SCHEDULE_HOST_DOWNTIME
	SCHEDULE_HOST_SVC_CHECKS
	SCHEDULE_HOST_SVC_DOWNTIME
	SCHEDULE_SERVICEGROUP_HOST_DOWNTIME
	SCHEDULE_SERVICEGROUP_SVC_DOWNTIME
	SCHEDULE_SVC_CHECK
	SCHEDULE_SVC_DOWNTIME
	SEND_CUSTOM_HOST_NOTIFICATION
	SEND_CUSTOM_SVC_NOTIFICATION
	SET_HOST_NOTIFICATION_NUMBER
	SET_SVC_NOTIFICATION_NUMBER
	SHUTDOWN_PROGRAM
	START_ACCEPTING_PASSIVE_HOST_CHECKS
	START_ACCEPTING_PASSIVE_SVC_CHECKS
	START_EXECUTING_HOST_CHECKS
	START_EXECUTING_SVC_CHECKS
	START_OBSESSING_OVER_HOST
	START_OBSESSING_OVER_HOST_CHECKS
	START_OBSESSING_OVER_SVC
	START_OBSESSING_OVER_SVC_CHECKS
	STOP_ACCEPTING_PASSIVE_HOST_CHECKS
	STOP_ACCEPTING_PASSIVE_SVC_CHECKS
	STOP_EXECUTING_HOST_CHECKS
	STOP_EXECUTING_SVC_CHECKS
	STOP_OBSESSING_OVER_HOST
	STOP_OBSESSING_OVER_HOST_CHECKS
	STOP_OBSESSING_OVER_SVC
	STOP_OBSESSING_OVER_SVC_CHECKS
)

type cmdTmpl struct {
	Name     string
	Pattern  string
	Defaults map[string]interface{}
	Required []string
}

var (
	nagiosCommands = map[int]cmdTmpl{
		ACKNOWLEDGE_HOST_PROBLEM: cmdTmpl{
			Name:    "ACKNOWLEDGE_HOST_PROBLEM",
			Pattern: "{{.host}};{{.sticky}};{{.notify}};{{.persistent}};{{.author}};{{.comment}}",

			Defaults: map[string]interface{}{
				"sticky":     2,
				"notify":     1,
				"persistent": 1,
			},
			Required: []string{
				"host",
			},
		},
		ACKNOWLEDGE_SVC_PROBLEM:                        cmdTmpl{},
		ADD_HOST_COMMENT:                               cmdTmpl{},
		ADD_SVC_COMMENT:                                cmdTmpl{},
		CHANGE_CONTACT_HOST_NOTIFICATION_TIMEPERIOD:    cmdTmpl{},
		CHANGE_CONTACT_MODATTR:                         cmdTmpl{},
		CHANGE_CONTACT_MODHATTR:                        cmdTmpl{},
		CHANGE_CONTACT_MODSATTR:                        cmdTmpl{},
		CHANGE_CONTACT_SVC_NOTIFICATION_TIMEPERIOD:     cmdTmpl{},
		CHANGE_CUSTOM_CONTACT_VAR:                      cmdTmpl{},
		CHANGE_CUSTOM_HOST_VAR:                         cmdTmpl{},
		CHANGE_CUSTOM_SVC_VAR:                          cmdTmpl{},
		CHANGE_GLOBAL_HOST_EVENT_HANDLER:               cmdTmpl{},
		CHANGE_GLOBAL_SVC_EVENT_HANDLER:                cmdTmpl{},
		CHANGE_HOST_CHECK_COMMAND:                      cmdTmpl{},
		CHANGE_HOST_CHECK_TIMEPERIOD:                   cmdTmpl{},
		CHANGE_HOST_EVENT_HANDLER:                      cmdTmpl{},
		CHANGE_HOST_MODATTR:                            cmdTmpl{},
		CHANGE_MAX_HOST_CHECK_ATTEMPTS:                 cmdTmpl{},
		CHANGE_MAX_SVC_CHECK_ATTEMPTS:                  cmdTmpl{},
		CHANGE_NORMAL_HOST_CHECK_INTERVAL:              cmdTmpl{},
		CHANGE_NORMAL_SVC_CHECK_INTERVAL:               cmdTmpl{},
		CHANGE_RETRY_HOST_CHECK_INTERVAL:               cmdTmpl{},
		CHANGE_RETRY_SVC_CHECK_INTERVAL:                cmdTmpl{},
		CHANGE_SVC_CHECK_COMMAND:                       cmdTmpl{},
		CHANGE_SVC_CHECK_TIMEPERIOD:                    cmdTmpl{},
		CHANGE_SVC_EVENT_HANDLER:                       cmdTmpl{},
		CHANGE_SVC_MODATTR:                             cmdTmpl{},
		CHANGE_SVC_NOTIFICATION_TIMEPERIOD:             cmdTmpl{},
		DELAY_HOST_NOTIFICATION:                        cmdTmpl{},
		DELAY_SVC_NOTIFICATION:                         cmdTmpl{},
		DEL_ALL_HOST_COMMENTS:                          cmdTmpl{},
		DEL_ALL_SVC_COMMENTS:                           cmdTmpl{},
		DEL_HOST_COMMENT:                               cmdTmpl{},
		DEL_HOST_DOWNTIME:                              cmdTmpl{},
		DEL_SVC_COMMENT:                                cmdTmpl{},
		DEL_SVC_DOWNTIME:                               cmdTmpl{},
		DISABLE_ALL_NOTIFICATIONS_BEYOND_HOST:          cmdTmpl{},
		DISABLE_CONTACTGROUP_HOST_NOTIFICATIONS:        cmdTmpl{},
		DISABLE_CONTACTGROUP_SVC_NOTIFICATIONS:         cmdTmpl{},
		DISABLE_CONTACT_HOST_NOTIFICATIONS:             cmdTmpl{},
		DISABLE_CONTACT_SVC_NOTIFICATIONS:              cmdTmpl{},
		DISABLE_EVENT_HANDLERS:                         cmdTmpl{},
		DISABLE_FAILURE_PREDICTION:                     cmdTmpl{},
		DISABLE_FLAP_DETECTION:                         cmdTmpl{},
		DISABLE_HOSTGROUP_HOST_CHECKS:                  cmdTmpl{},
		DISABLE_HOSTGROUP_HOST_NOTIFICATIONS:           cmdTmpl{},
		DISABLE_HOSTGROUP_PASSIVE_HOST_CHECKS:          cmdTmpl{},
		DISABLE_HOSTGROUP_PASSIVE_SVC_CHECKS:           cmdTmpl{},
		DISABLE_HOSTGROUP_SVC_CHECKS:                   cmdTmpl{},
		DISABLE_HOSTGROUP_SVC_NOTIFICATIONS:            cmdTmpl{},
		DISABLE_HOST_AND_CHILD_NOTIFICATIONS:           cmdTmpl{},
		DISABLE_HOST_CHECK:                             cmdTmpl{},
		DISABLE_HOST_EVENT_HANDLER:                     cmdTmpl{},
		DISABLE_HOST_FLAP_DETECTION:                    cmdTmpl{},
		DISABLE_HOST_FRESHNESS_CHECKS:                  cmdTmpl{},
		DISABLE_HOST_NOTIFICATIONS:                     cmdTmpl{},
		DISABLE_HOST_SVC_CHECKS:                        cmdTmpl{},
		DISABLE_HOST_SVC_NOTIFICATIONS:                 cmdTmpl{},
		DISABLE_NOTIFICATIONS:                          cmdTmpl{},
		DISABLE_PASSIVE_HOST_CHECKS:                    cmdTmpl{},
		DISABLE_PASSIVE_SVC_CHECKS:                     cmdTmpl{},
		DISABLE_PERFORMANCE_DATA:                       cmdTmpl{},
		DISABLE_SERVICEGROUP_HOST_CHECKS:               cmdTmpl{},
		DISABLE_SERVICEGROUP_HOST_NOTIFICATIONS:        cmdTmpl{},
		DISABLE_SERVICEGROUP_PASSIVE_HOST_CHECKS:       cmdTmpl{},
		DISABLE_SERVICEGROUP_PASSIVE_SVC_CHECKS:        cmdTmpl{},
		DISABLE_SERVICEGROUP_SVC_CHECKS:                cmdTmpl{},
		DISABLE_SERVICEGROUP_SVC_NOTIFICATIONS:         cmdTmpl{},
		DISABLE_SERVICE_FLAP_DETECTION:                 cmdTmpl{},
		DISABLE_SERVICE_FRESHNESS_CHECKS:               cmdTmpl{},
		DISABLE_SVC_CHECK:                              cmdTmpl{},
		DISABLE_SVC_EVENT_HANDLER:                      cmdTmpl{},
		DISABLE_SVC_FLAP_DETECTION:                     cmdTmpl{},
		DISABLE_SVC_NOTIFICATIONS:                      cmdTmpl{},
		ENABLE_ALL_NOTIFICATIONS_BEYOND_HOST:           cmdTmpl{},
		ENABLE_CONTACTGROUP_HOST_NOTIFICATIONS:         cmdTmpl{},
		ENABLE_CONTACTGROUP_SVC_NOTIFICATIONS:          cmdTmpl{},
		ENABLE_CONTACT_HOST_NOTIFICATIONS:              cmdTmpl{},
		ENABLE_CONTACT_SVC_NOTIFICATIONS:               cmdTmpl{},
		ENABLE_EVENT_HANDLERS:                          cmdTmpl{},
		ENABLE_FAILURE_PREDICTION:                      cmdTmpl{},
		ENABLE_FLAP_DETECTION:                          cmdTmpl{},
		ENABLE_HOSTGROUP_HOST_CHECKS:                   cmdTmpl{},
		ENABLE_HOSTGROUP_HOST_NOTIFICATIONS:            cmdTmpl{},
		ENABLE_HOSTGROUP_PASSIVE_HOST_CHECKS:           cmdTmpl{},
		ENABLE_HOSTGROUP_PASSIVE_SVC_CHECKS:            cmdTmpl{},
		ENABLE_HOSTGROUP_SVC_CHECKS:                    cmdTmpl{},
		ENABLE_HOSTGROUP_SVC_NOTIFICATIONS:             cmdTmpl{},
		ENABLE_HOST_AND_CHILD_NOTIFICATIONS:            cmdTmpl{},
		ENABLE_HOST_CHECK:                              cmdTmpl{},
		ENABLE_HOST_EVENT_HANDLER:                      cmdTmpl{},
		ENABLE_HOST_FLAP_DETECTION:                     cmdTmpl{},
		ENABLE_HOST_FRESHNESS_CHECKS:                   cmdTmpl{},
		ENABLE_HOST_NOTIFICATIONS:                      cmdTmpl{},
		ENABLE_HOST_SVC_CHECKS:                         cmdTmpl{},
		ENABLE_HOST_SVC_NOTIFICATIONS:                  cmdTmpl{},
		ENABLE_NOTIFICATIONS:                           cmdTmpl{},
		ENABLE_PASSIVE_HOST_CHECKS:                     cmdTmpl{},
		ENABLE_PASSIVE_SVC_CHECKS:                      cmdTmpl{},
		ENABLE_PERFORMANCE_DATA:                        cmdTmpl{},
		ENABLE_SERVICEGROUP_HOST_CHECKS:                cmdTmpl{},
		ENABLE_SERVICEGROUP_HOST_NOTIFICATIONS:         cmdTmpl{},
		ENABLE_SERVICEGROUP_PASSIVE_HOST_CHECKS:        cmdTmpl{},
		ENABLE_SERVICEGROUP_PASSIVE_SVC_CHECKS:         cmdTmpl{},
		ENABLE_SERVICEGROUP_SVC_CHECKS:                 cmdTmpl{},
		ENABLE_SERVICEGROUP_SVC_NOTIFICATIONS:          cmdTmpl{},
		ENABLE_SERVICE_FRESHNESS_CHECKS:                cmdTmpl{},
		ENABLE_SVC_CHECK:                               cmdTmpl{},
		ENABLE_SVC_EVENT_HANDLER:                       cmdTmpl{},
		ENABLE_SVC_FLAP_DETECTION:                      cmdTmpl{},
		ENABLE_SVC_NOTIFICATIONS:                       cmdTmpl{},
		PROCESS_FILE:                                   cmdTmpl{},
		PROCESS_HOST_CHECK_RESULT:                      cmdTmpl{},
		PROCESS_SERVICE_CHECK_RESULT:                   cmdTmpl{},
		READ_STATE_INFORMATION:                         cmdTmpl{},
		REMOVE_HOST_ACKNOWLEDGEMENT:                    cmdTmpl{},
		REMOVE_SVC_ACKNOWLEDGEMENT:                     cmdTmpl{},
		RESTART_PROGRAM:                                cmdTmpl{},
		SAVE_STATE_INFORMATION:                         cmdTmpl{},
		SCHEDULE_AND_PROPAGATE_HOST_DOWNTIME:           cmdTmpl{},
		SCHEDULE_AND_PROPAGATE_TRIGGERED_HOST_DOWNTIME: cmdTmpl{},
		SCHEDULE_FORCED_HOST_CHECK:                     cmdTmpl{},
		SCHEDULE_FORCED_HOST_SVC_CHECKS:                cmdTmpl{},
		SCHEDULE_FORCED_SVC_CHECK:                      cmdTmpl{},
		SCHEDULE_HOSTGROUP_HOST_DOWNTIME:               cmdTmpl{},
		SCHEDULE_HOSTGROUP_SVC_DOWNTIME:                cmdTmpl{},
		SCHEDULE_HOST_CHECK:                            cmdTmpl{},
		SCHEDULE_HOST_DOWNTIME:                         cmdTmpl{},
		SCHEDULE_HOST_SVC_CHECKS:                       cmdTmpl{},
		SCHEDULE_HOST_SVC_DOWNTIME:                     cmdTmpl{},
		SCHEDULE_SERVICEGROUP_HOST_DOWNTIME:            cmdTmpl{},
		SCHEDULE_SERVICEGROUP_SVC_DOWNTIME:             cmdTmpl{},
		SCHEDULE_SVC_CHECK:                             cmdTmpl{},
		SCHEDULE_SVC_DOWNTIME: cmdTmpl{
			Name:    "SCHEDULE_SVC_DOWNTIME",
			Pattern: "{{.host_name}};{{.service}},{{.start_time}};{{.end_time}};{{.fixed}};{{.trigger_id}};{{.duration}};{{.author};{{.comment}}",
			Defaults: map[string]interface{}{
				"duration":   600,
				"fixed":      1,
				"trigger_id": 0,
				"author":     "default",
				"comment":    "",
			},
			Required: []string{
				"host", "service", "start_time", "end_time",
			},
		},
		SEND_CUSTOM_HOST_NOTIFICATION:       cmdTmpl{},
		SEND_CUSTOM_SVC_NOTIFICATION:        cmdTmpl{},
		SET_HOST_NOTIFICATION_NUMBER:        cmdTmpl{},
		SET_SVC_NOTIFICATION_NUMBER:         cmdTmpl{},
		SHUTDOWN_PROGRAM:                    cmdTmpl{},
		START_ACCEPTING_PASSIVE_HOST_CHECKS: cmdTmpl{},
		START_ACCEPTING_PASSIVE_SVC_CHECKS:  cmdTmpl{},
		START_EXECUTING_HOST_CHECKS:         cmdTmpl{},
		START_EXECUTING_SVC_CHECKS:          cmdTmpl{},
		START_OBSESSING_OVER_HOST:           cmdTmpl{},
		START_OBSESSING_OVER_HOST_CHECKS:    cmdTmpl{},
		START_OBSESSING_OVER_SVC:            cmdTmpl{},
		START_OBSESSING_OVER_SVC_CHECKS:     cmdTmpl{},
		STOP_ACCEPTING_PASSIVE_HOST_CHECKS:  cmdTmpl{},
		STOP_ACCEPTING_PASSIVE_SVC_CHECKS:   cmdTmpl{},
		STOP_EXECUTING_HOST_CHECKS:          cmdTmpl{},
		STOP_EXECUTING_SVC_CHECKS:           cmdTmpl{},
		STOP_OBSESSING_OVER_HOST:            cmdTmpl{},
		STOP_OBSESSING_OVER_HOST_CHECKS:     cmdTmpl{},
		STOP_OBSESSING_OVER_SVC:             cmdTmpl{},
		STOP_OBSESSING_OVER_SVC_CHECKS:      cmdTmpl{},
	}
)

func FormCommand(op int, args map[string]interface{}) (string, error) {
	tmpl, err := template.New("op").Parse(nagiosCommands[op].Pattern)
	if err != nil {
		return "", err
	}
	buf := bytes.NewBufferString("")
	err = tmpl.Execute(buf, args)
	if err != nil {
		panic(err)
	}
	return fmt.Sprintf("[%d] %s;%s\n", time.Now().Unix(), nagiosCommands[op].Name, buf.String()), nil
}

func writeCommand(cmdstring string) error {
	cmdmutex.Lock()
	defer cmdmutex.Unlock()
	fp, err := os.Open(*commandPath)
	if err != nil {
		return err
	}
	_, err = fmt.Fprintf(fp, cmdstring)
	if err != nil {
		return err
	}
	return nil
}
